name: "Auto Assign"
on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Assign PR
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          addAssignees: true
          numberOfAssignees: 1
          assignees: ${{ github.repository_collaborators }}
          randomAssignees: true