name: Node CI

on: [push]

permissions:
  id-token: write  # Required for OIDC
  contents: write

jobs:
  build:
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          version: 12
          runtime: node@${{ matrix.node }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: pnpm install, build, and test
        run: |
          pnpm install --frozen-lockfile --ignore-scripts
          pnpm build:prod
          pnpm test
        env:
          CI: true
      - name: lint
        run: |
          pnpm lint:js
          pnpm lint:css
        env:
          CI: true

  publish:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          version: 12
          runtime: node@${{ matrix.node }}
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm build:prod
      - run: pnpm test
      - uses: JS-DevTools/npm-publish@0fd2f4369c5d6bcfcde6091a7c527d810b9b5c3f # v4.1.5
        id: publishNpm
        with:
          dry-run: false
      - if: ${{ steps.publishNpm.outputs.type }}
        run: gh release create ${{ steps.publishNpm.outputs.version }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
